### PR TITLE
use newer style of JRuby ext loading when available

### PR DESCRIPTION
**Pull request by kares**
JRuby load_ext details at https://github.com/jruby/jruby/pull/5205

### CODE REVIEW

**Comment by kares** [comment]
added some (more) commits on top of the original. 

haven seen a non-existent `SNAKEYAML_VERSION` - was really confusing to see `"1.21.0"` (for 1.21), 
I am also not sure about stripping the `SNAPSHOT` that seems to be related and no longer necessary?

**Comment by hsbt** [comment]
@headius Can you review this?

**Comment by headius** [comment]
@hsbt This looks ok. We would like to get 3.0.3 released so we can resolve https://github.com/jruby/jruby/issues/5098. I'll merge this manually.

**Comment by headius** [comment]
I have merged in the primary change here (new ext loading) and made other fixes to the handling of the default SnakeYAML version in the Rakefile. This is ready to go.

**Comment by kares** [comment]
great, thanks - also it was really confusing that ".0" is always added to snake-yaml's version.
... although pbly not many people will look into that, reminder for myself that https://github.com/ruby/psych/pull/365/commits/bfd7b14243c37318189a0f6dc33386ab625ce750 is **not** in

**Pull request closed without merging**
