### PR TITLE
instructions for macports users

### PR DESCRIPTION
**Pull request by jjb**
This is probably not the best place to put this

and/or we can just add brew as well?

for homebrew, are the flags needed, or does it look in those paths by default?

can/should the project look into the macports paths by default as well?

### CODE REVIEW

**Comment by tenderlove** [comment]
Homebrew provides pkg-config files for libyaml, so I think that's how [Psych picks it up](https://github.com/ruby/psych/blob/be0ba74e5613c20f213403e15914d24944c2652d/ext/psych/extconf.rb#L40-L41).

Are you able to do this?

```
$ pkg-config --list-all | grep yaml
yaml-0.1          LibYAML - Library to parse and emit YAML
```

**Comment by jjb** [comment]
```
pkg-config --list-all | grep yaml
```

**Comment by jjb** [comment]
```
sudo port install pkgconfig

## open new terminal.....

➔ pkg-config --list-all | grep yaml
yaml-cpp        Yaml-cpp - A YAML parser and emitter for C++
yaml-0.1        LibYAML - Library to parse and emit YAML
```

**Comment by jjb** [comment]
```
sudo port uninstall pkgconfig
mv .bundle/config .bundle/config-back
gem uninstall psych
## open new window
gem install psych
# it breaks!
sudo port install pkgconfig
## open new terminal
gem install psych
# it works!
```

ARE YOU KIDDING ME
HOW HAVE I BEEN PROGRAMMING FOR 23 YEARS AND DIDN'T KNOW ABOUT THIS

**Pull request closed without merging**
